name: Test all distros
on:
  push:
    branches: [main]
jobs:
  run-commands:
    name: "[${{ matrix.package.name }}]-${{ matrix.image }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - { name: make, validate: "make --version" }
          - { name: nano, validate: "nano --version" }
          - { name: gcc, validate: "gcc --version" }
          - { name: gdb, validate: "gdb --version" }
          - { name: cmake, validate: "cmake --version" }
          - { name: git, validate: "git --version" }
          - { name: clang, validate: "clang --version" }
        image:
          - fedora37
          - fedora38
          - almalinux8
          - almalinux9
          # - centos7
          - debian10
          - debian11
          - rockylinux8
          - rockylinux9
          - suse15
          - sles15
          - ubuntu20_04
          - ubuntu22_04
          - rhel8
          - rhel9
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.image }} [${{ matrix.package.name }}]
        run: test/test.sh Dockerfile.${{ matrix.image }} ${{ matrix.package.name }} "${{ matrix.package.validate }}"
