name: Test all distros
on:
  push:
    branches: [main]
jobs:
  run-commands:
    name: ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - { name: make, validate: "make --version" }
          - { name: nano, validate: "nano --version" }
          - { name: gcc, validate: "gcc --version" }
          - { name: gdb, validate: "gdb --version" }
          - { name: cmake, validate: "cmake --version" }
        image:
          - Dockerfile.fedora37
          - Dockerfile.fedora38
          - Dockerfile.almalinux8
          - Dockerfile.almalinux9
          # - Dockerfile.centos7
          - Dockerfile.debian10
          - Dockerfile.debian11
          - Dockerfile.rockylinux8
          - Dockerfile.rockylinux9
          - Dockerfile.suse15
          - Dockerfile.sles15
          - Dockerfile.ubuntu20_04
          - Dockerfile.ubuntu22_04
          - Dockerfile.rhel8
          - Dockerfile.rhel9
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.image }} [${{ matrix.package.name }}]
        run: test/test.sh ${{ matrix.image }} ${{ matrix.package.name }} "${{ matrix.package.validate }}"
